name: Flight Scanner

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan-flights:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run scanner
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python flight_alert.py

      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          if [ ! -f flight_results.csv ]; then
            echo "flight_results.csv was not created. Nothing to commit."
            exit 0
          fi

          git add flight_results.csv

          if git diff --cached --quiet; then
            echo "No CSV changes to commit"
          else
            git commit -m "Auto update flight results"
            git push
          fi

      - name: Push CSV to dashboard repo
        run: |
          git clone https://x-access-token:${{ secrets.DASHBOARD_PUSH_TOKEN }}@github.com/8bwrj2g4ds-tech/flight-dashboard.git dashboard-temp

          cp flight_results.csv dashboard-temp/flight_results.csv

          cd dashboard-temp

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add flight_results.csv

          if git diff --cached --quiet; then
            echo "No dashboard CSV changes"
          else
            git commit -m "Update dashboard CSV"
            git push
          fi
